spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5431/ajudaadb
    username: ajudaadb
    password: ajudaadb
    driverClassName: org.postgresql.Driver